### 2018324031 Minseung Ko SARSA Code

In [2]:
import numpy as np

# set parameters ###############################################################
epoch = 1000
alpha = 0.01

# epsilon = 0.01
# should go to 0. For example, epsilon = 1 / (epoch_number+1)
# implemented below
# set parameters ###############################################################

# state
states = [0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10]
N_STATES = len(states)

# action
actions = [0, 1, 2, 3]
N_ACTIONS = len(actions)

# transition probabilities
P = np.empty((N_STATES, N_ACTIONS, N_STATES))

#                0   1   2   3   4   5   6   7   8   9  10
P[0, 0, :] = [.9, 0, 0, 0, .1, 0, 0, 0, 0, 0, 0]
P[0, 1, :] = [.1, .8, 0, 0, .1, 0, 0, 0, 0, 0, 0]
P[0, 2, :] = [.9, .1, 0, 0, 0, 0, 0, 0, 0, 0, 0]
P[0, 3, :] = [.1, .1, 0, 0, .8, 0, 0, 0, 0, 0, 0]

#                0   1   2   3   4   5   6   7   8   9  10
P[1, 0, :] = [.8, .2, 0, 0, 0, 0, 0, 0, 0, 0, 0]
P[1, 1, :] = [0, .2, .8, 0, 0, 0, 0, 0, 0, 0, 0]
P[1, 2, :] = [.1, .8, .1, 0, 0, 0, 0, 0, 0, 0, 0]
P[1, 3, :] = [.1, .8, .1, 0, 0, 0, 0, 0, 0, 0, 0]

#                0   1   2   3   4   5   6   7   8   9  10
P[2, 0, :] = [0, .8, .1, 0, 0, .1, 0, 0, 0, 0, 0]
P[2, 1, :] = [0, 0, .1, .8, 0, .1, 0, 0, 0, 0, 0]
P[2, 2, :] = [0, .1, .8, .1, 0, 0, 0, 0, 0, 0, 0]
P[2, 3, :] = [0, .1, 0, .1, 0, .8, 0, 0, 0, 0, 0]

#                0   1   2   3   4   5   6   7   8   9  10
P[3, 0, :] = [0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0]
P[3, 1, :] = [0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0]
P[3, 2, :] = [0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0]
P[3, 3, :] = [0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0]

#                0   1   2   3   4   5   6   7   8   9  10
P[4, 0, :] = [.1, 0, 0, 0, .8, 0, 0, .1, 0, 0, 0]
P[4, 1, :] = [.1, 0, 0, 0, .8, 0, 0, .1, 0, 0, 0]
P[4, 2, :] = [.8, 0, 0, 0, .2, 0, 0, 0, 0, 0, 0]
P[4, 3, :] = [0, 0, 0, 0, .2, 0, 0, .8, 0, 0, 0]

#                0   1   2   3   4   5   6   7   8   9  10
P[5, 0, :] = [0, 0, .1, 0, 0, .8, 0, 0, 0, .1, 0]
P[5, 1, :] = [0, 0, .1, 0, 0, 0, .8, 0, 0, .1, 0]
P[5, 2, :] = [0, 0, .8, 0, 0, .1, .1, 0, 0, 0, 0]
P[5, 3, :] = [0, 0, 0, 0, 0, .1, .1, 0, 0, .8, 0]

#                0   1   2   3   4   5   6   7   8   9  10
P[6, 0, :] = [0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0]
P[6, 1, :] = [0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0]
P[6, 2, :] = [0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0]
P[6, 3, :] = [0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0]

#                0   1   2   3   4   5   6   7   8   9  10
P[7, 0, :] = [0, 0, 0, 0, .1, 0, 0, .9, 0, 0, 0]
P[7, 1, :] = [0, 0, 0, 0, .1, 0, 0, .1, .8, 0, 0]
P[7, 2, :] = [0, 0, 0, 0, .8, 0, 0, .1, .1, 0, 0]
P[7, 3, :] = [0, 0, 0, 0, 0, 0, 0, .9, .1, 0, 0]

#                0   1   2   3   4   5   6   7   8   9  10
P[8, 0, :] = [0, 0, 0, 0, 0, 0, 0, .8, .2, 0, 0]
P[8, 1, :] = [0, 0, 0, 0, 0, 0, 0, 0, .2, .8, 0]
P[8, 2, :] = [0, 0, 0, 0, 0, 0, 0, .1, .8, .1, 0]
P[8, 3, :] = [0, 0, 0, 0, 0, 0, 0, .1, .8, .1, 0]

#                0   1   2   3   4   5   6   7   8   9  10
P[9, 0, :] = [0, 0, 0, 0, 0, .1, 0, 0, .8, .1, 0]
P[9, 1, :] = [0, 0, 0, 0, 0, .1, 0, 0, 0, .1, .8]
P[9, 2, :] = [0, 0, 0, 0, 0, .8, 0, 0, .1, 0, .1]
P[9, 3, :] = [0, 0, 0, 0, 0, 0, 0, 0, .1, .8, .1]

#                0   1   2   3   4   5   6   7   8   9  10
P[10, 0, :] = [0, 0, 0, 0, 0, 0, .1, 0, 0, .8, .1]
P[10, 1, :] = [0, 0, 0, 0, 0, 0, .1, 0, 0, 0, .9]
P[10, 2, :] = [0, 0, 0, 0, 0, 0, .8, 0, 0, .1, .1]
P[10, 3, :] = [0, 0, 0, 0, 0, 0, 0, 0, 0, .1, .9]

# rewards
R = -0.02 * np.ones((N_STATES, N_ACTIONS))
R[3, :] = 1.
R[6, :] = -1.

# discount factor
gamma = 0.95

# policy
if 0:
    # bad policy
    policy = np.empty((N_STATES, N_ACTIONS))
    policy[0, :] = [0, 1, 0, 0]
    policy[1, :] = [0, 1, 0, 0]
    policy[2, :] = [0, 1, 0, 0]
    policy[3, :] = [0, 1, 0, 0]
    policy[4, :] = [0, 0, 0, 1]
    policy[5, :] = [0, 1, 0, 0]
    policy[6, :] = [0, 1, 0, 0]
    policy[7, :] = [0, 1, 0, 0]
    policy[8, :] = [0, 1, 0, 0]
    policy[9, :] = [0, 0, 1, 0]
    policy[10, :] = [0, 0, 1, 0]
elif 1:
    # random policy
    policy = 0.25 * np.ones((N_STATES, N_ACTIONS))
elif 1:
    # optimal policy
    policy = np.empty((N_STATES, N_ACTIONS))
    policy[0, :] = [0, 1, 0, 0]
    policy[1, :] = [0, 1, 0, 0]
    policy[2, :] = [0, 1, 0, 0]
    policy[3, :] = [0, 1, 0, 0]
    policy[4, :] = [0, 0, 1, 0]
    policy[5, :] = [0, 0, 1, 0]
    policy[6, :] = [0, 0, 1, 0]
    policy[7, :] = [0, 0, 1, 0]
    policy[8, :] = [1, 0, 0, 0]
    policy[9, :] = [1, 0, 0, 0]
    policy[10, :] = [1, 0, 0, 0]
elif 1:
    # optimal policy + noise
    # we use optimal policy with probability 1/(1+ep)
    # we use random policy with probability ep/(1+ep)
    ep = 0.1
    policy = np.empty((N_STATES, N_ACTIONS))
    policy[0, :] = [0, 1, 0, 0]
    policy[1, :] = [0, 1, 0, 0]
    policy[2, :] = [0, 1, 0, 0]
    policy[3, :] = [0, 1, 0, 0]
    policy[4, :] = [0, 0, 1, 0]
    policy[5, :] = [0, 0, 1, 0]
    policy[6, :] = [0, 0, 1, 0]
    policy[7, :] = [0, 0, 1, 0]
    policy[8, :] = [1, 0, 0, 0]
    policy[9, :] = [1, 0, 0, 0]
    policy[10, :] = [1, 0, 0, 0]
    policy = policy + (ep / 4) * np.ones((N_STATES, N_ACTIONS))
    policy = policy / np.sum(policy, axis=1).reshape((N_STATES, 1))

" SARSA "

# Q
Q = np.zeros((N_STATES, N_ACTIONS))
Q[3, :] = 1.
Q[6, :] = -1.

for epoch_number in range(epoch):
    alpha = 0.75*(epoch-epoch_number+1)/(epoch+1)
    epsilon = 0.03
    # indicate game is not over yet
    done = False

    # choose initial state randomly, not from 3 or 6
    s = np.random.choice([0, 1, 2, 4, 5, 7, 8, 9, 10])

    # this is policy update part of algorithm
    # epsilon-greedy policy update
    # choose action using udated epsilon-greedy policy
    # if this part is replaced and if we choose action using current policy
    # this whole algorithm becomes TD, not SARSA, SARSA(lambda) nor Q-Learning
    if np.random.uniform(0., 1.) < epsilon:
        # random action selection
        a = np.random.choice(actions)
    else:
        # greedy action selection
        a = np.argmax(Q[s, :])

    while not done:
        # choose next state using transition probabilities
        s1 = np.random.choice(states, p=P[s, a, :])

        # this is policy update part of algorithm
        # epsilon-greedy policy update
        # choose action using udated epsilon-greedy policy
        # if this part is replaced and if we choose action using current policy
        # this whole algorithm becomes TD, not SARSA, SARSA(lambda) nor Q-Learning
        if np.random.uniform(0., 1.) < epsilon:
            # random action selection
            a1 = np.random.choice(actions)
        else:
            # greedy action selection
            a1 = np.argmax(Q[s1, :])

        # this is policy estimate part of algorithm
        # this part is identical to TD
        Q[s, a] += alpha * (R[s, a] + gamma * Q[s1, a1] - Q[s, a])

        if (s1 == 3) or (s1 == 6):
            # if game is over, break while loop
            done = True
        else:
            # if game is not over, continue playing game
            s = s1
            a = a1

print(Q)
Q_argmax = np.zeros(11)
Q_order = []

for i in range(11):
    Q_argmax[i] = np.argmax(Q[i, :])
    if Q_argmax[i] == 0:
        Q_order.append('left')
    elif Q_argmax[i] == 1:
        Q_order.append('right')
    elif Q_argmax[i] == 2:
        Q_order.append('up')
    else:
        Q_order.append('down')
Q_order[3]='x'
Q_order[6]='y'
print(Q_order)

[[ 0.56014293  0.72209792  0.11842894  0.31268632]
 [ 0.31887562  0.79933761  0.60682552  0.52018265]
 [ 0.53914766  0.87533101  0.61347706  0.35298838]
 [ 1.          1.          1.          1.        ]
 [ 0.51215675  0.44185619  0.65970279  0.43839378]
 [-0.31916784 -0.9577339   0.68906589 -0.44564525]
 [-1.         -1.         -1.         -1.        ]
 [ 0.29525866  0.29649233  0.58169913  0.36550078]
 [ 0.51606246  0.16324046  0.28663181  0.07424711]
 [ 0.43114965 -0.14035901  0.06463499  0.19447393]
 [ 0.13458322 -0.72362503 -0.96350732 -0.62062686]]
['right', 'right', 'right', 'x', 'up', 'up', 'y', 'up', 'left', 'left', 'left']
